### ISSUE TITLE
Can't change locale in phpcensor.

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#11]
Now it throws an error when I try to do it:
``` SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" ```

**Comment by ket4yii** [comment]
N.B. it happens only in web. If I change it by config it works fine.

**Comment by corpsee** [comment]
Are you change locale for user?

**Comment by corpsee** [comment]
Do you change locale for user? What DB type? 

I could not reproduce :(

**Comment by ket4yii** [comment]
PGSQL, tried to change for admin user.

**Comment by ket4yii** [comment]
Tried to do it with my docker-compose file.

**Comment by corpsee** [comment]
Ok, I will try to reproduce

**Comment by corpsee** [comment]
Fixed. @ket4yii Can you check it, please?

**Comment by ket4yii** [comment]
Cool. I'm gonna check it ASAP.
