### ISSUE TITLE
[BUG] worker doesn't reload config between build

### ISSUE THREAD

**Issue by vinpel** [corpsee/php-censor#17]
Two case :

- Adding a projet will FAIL to build with error :
```bash
Exception: Could not create a working copy.

BUILD FAILED
Exception: Warning: array_key_exists() expects parameter 2 to be array, null given in /data/htdocs/phpci/src/PHPCensor/Plugin/Util/Executor.php line 58
```
 - Every edit in php structure is not taken into account BEFORE i send a HUP signal to my worker

**Comment by corpsee** [comment]
1. Ок, I will try to fix it soon

2. See #7

**Comment by corpsee** [comment]
@vinpel Can you check your first case in branch `bugfix-worker-config`?

**Comment by vinpel** [comment]
seem fine now

**Comment by corpsee** [comment]
Thanks
