### ISSUE TITLE
[Bug] test github repo

### ISSUE THREAD

**Issue by vinpel** [corpsee/php-censor#20]
without Github token i créate a project :

"https://github.com/vinpel/php-Crypto"
empty private key
validate

when i try to test it i get :

```

Cloning into '/data/htdocs/php-censor/runtime/builds/13_78102'...
remote: Not Found
fatal: repository 'https://github.com/https://github.com/vinpel/php-Crypto.git/' not found

Failed to clone remote git repository.
Exception: Could not create a working copy.

BUILD FAILED
Exception: Warning: array_key_exists() expects parameter 2 to be array, null given in /data/htdocs/phpci/src/PHPCensor/Plugin/Util/Executor.php line 58

Removing Build.
```

maybe in case of clone error can you show the full command ?
here my path is duplicated multiple time

with "vinpel/php-Crypto" it work fine

**Comment by corpsee** [comment]
I will plan to rework 'create project' page soon. I agree that it is strange behavior.

**Comment by vinpel** [comment]
I will list all the things for the create project

**Comment by vinpel** [comment]
- Creating a projet is not set to  github field "Choose a GitHub repository:" still visible
- All error message must be more visible (red maybe)
- SSH key generated disappear if  get a validation error message
- Maybe test if possible if the repositories/directory is accessible : 
    - host respond to ping / DNS
    - repository exist
    - no authorization problem
- add for Gogs and maybe other a basic auth method
- yaml field is not validated  (something like http://symfony.com/doc/current/components/yaml.html maybe, not tested)
- if no key generated, a guide with what package needed can help

today lot of test and error to have a valid config.
Maybe a button to fill the "PHP Censor build config for " with what a zero config do

a lot more example may be needed with basic case.

A default project to test against may be needed to validate the php-censor installation.
Ex : if you want to test the php-censor installation, simple add a project with this repo, this config and launch to test !

**Comment by corpsee** [comment]
Thank you for cases, @vinpel!

**Comment by corpsee** [comment]
Bug with repository reference from first message fixed. @vinpel Can you check it?

**Comment by vinpel** [comment]
Bug is still present 
i have HUP the worker, no change

My configuration (you can create the same project) :
(rest is empty)
![config](https://cloud.githubusercontent.com/assets/1699839/23014603/ef3e1290-f42f-11e6-8285-0a76448e13bd.png)

**Comment by corpsee** [comment]
Are you sure that use latest master branch? I can not reproduce your case.
When I insert something like `https://github.com/<user>/<repository>` the input change it to `<user>/<repository>` and git clone work normally:
```json
Command: git clone --recursive  -b master https://github.com/<user>/<repository>.git "/"
```

**Comment by vinpel** [comment]
oh i got it ...

i have the last commit, BUT during my test i have forget to made the "composer install" 


... and codemirror asset was not installed => javascript not working fine on the page 

so yes it work in the last commit, so it work fine !

**Comment by corpsee** [comment]
Great, thank you)
