### ISSUE TITLE
Logo for PHP Censor.

### ISSUE THREAD

**Issue by ketchoop** [corpsee/php-censor#29]
What about logo?) Because, sometimes I publishing containers and docker-compose files in some community repos and want to publish PHPCensor. With logo it'll be better:smile:.

**Comment by corpsee** [comment]
I will try to make something, but I am not a good designer :smile:

**Comment by corpsee** [comment]
The first horrible try 😈
![3](https://cloud.githubusercontent.com/assets/1416706/24586739/d9b15534-17d1-11e7-831f-003340d2dfa1.png)

**Comment by JoolsMcFly** [comment]
Ha ha nice try. I'll try to come up with something this week, see if I can do worse. :D

**Comment by corpsee** [comment]
Ok :D

**Comment by ket4yii** [comment]
@corpsee Not bad as it would be :smiley:

**Comment by JoolsMcFly** [comment]
OK, how about these two versions for starters:


![image](https://cloud.githubusercontent.com/assets/4972399/24758138/a96d0b30-1ae1-11e7-9b05-360e13cbd9d6.png)


or


![image](https://cloud.githubusercontent.com/assets/4972399/24758151/b6efa31c-1ae1-11e7-9213-bedb867bf44b.png)

**Comment by JoolsMcFly** [comment]
And a third one which I prefer:
![image](https://cloud.githubusercontent.com/assets/4972399/24758389/82276146-1ae2-11e7-92ce-f82c906d92c4.png)

**Comment by corpsee** [comment]
I would consider more variants :smile:

**Comment by JoolsMcFly** [comment]
Dayum! You no likey the third one then?

Look at it, it's a cute elePHPhant!

**Comment by corpsee** [comment]
I want more variants) Let the issue remain open for now.

**Comment by vinpel** [comment]
A try : 
![logo](https://cloud.githubusercontent.com/assets/1699839/24964506/c282fcaa-1fa1-11e7-8d02-70929a9d46c6.png)

**Comment by corpsee** [comment]
It looks not bad:)

**Comment by vinpel** [comment]
![logov2](https://cloud.githubusercontent.com/assets/1699839/24997384/c1dfe002-2036-11e7-9906-433e1bb50f81.png)

**Comment by corpsee** [comment]
![php-censor-3](https://user-images.githubusercontent.com/1416706/29246704-22720034-802d-11e7-8bcb-7ca86beb7b48.png)

**Comment by corpsee** [comment]
![111](https://user-images.githubusercontent.com/1416706/29277274-5f449f9e-813b-11e7-9a60-ba261f6bd352.png)

**Comment by corpsee** [comment]
@vinpel, @ketchoop, @valeriitropin, @JoolsMcFly, @ss-gxp, @bochkovprivate, @StudioMaX, @SimonHeimberg, @LEXASOFT What do you think about the latest logo? I propose to take it and close this issue.

**Comment by ketchoop** [comment]
LGTM

**Comment by vinpel** [comment]
industrial look, but lgtm for me

**Comment by corpsee** [comment]
@ketchoop @vinpel Thanks. Excellent)

**Comment by corpsee** [comment]
It is done! [Logo images](https://github.com/corpsee/php-censor/tree/master/docs/images).
