### ISSUE TITLE
Localization troubles

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#3]
When you run php-censor:install the first question is: %%MISSING STRING: enter_db_type%%.

P.S. Please, don't close this issue after you work it out. If I find some troubles with a l8n I will post them here.

**Comment by corpsee** [comment]
I removed localization from console commands (Because it doesn't work). @ket4yii, Can you check your issue in the master branch?

**Comment by ket4yii** [comment]
@corpsee it's ok.
