### ISSUE TITLE
branch name in HomeController

### ISSUE THREAD

**Issue by JoolsMcFly** [corpsee/php-censor#32]
Hi,

at work we build multiple branches and it would be nice, in HomeController, to display the branch name a build was run on.

I modified our own copy of PHPCI to do that, including a dedicated check box in project edit form.
I am willing to port these changes over to php-censor. Would it be OK if I did that? If so, I'll make a PR for it later.

Waiting for your feeback.

Thanks!

**Comment by corpsee** [comment]
Hi. I already implement it (I saw your PHPCI pull request) :smiling_imp: 
![branch](https://cloud.githubusercontent.com/assets/1416706/23956874/6a21e972-09d0-11e7-91f7-ff373ab12705.png).

Can you check it is ok for you? Thanks)

**Comment by JoolsMcFly** [comment]
I see! Very good, it does the trick.

Now I added something else next to the build time: build duration.
![image](https://cloud.githubusercontent.com/assets/4972399/23970363/c8987ec8-09c9-11e7-8fe9-4ab9b3c1c20a.png)

What do you think? Worth a PR and new issue?

**Comment by corpsee** [comment]
Yes, create new PR with it and close this issue.

**Comment by JoolsMcFly** [comment]
Sounds good, I'll do that soon.
