### ISSUE TITLE
Something wrong with Plugin

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#38]
Maybe backward compatibility was broken:

RUNNING PLUGIN: \Ket4yii\PHPCI\Deployer\Plugin\Deployer (Stage: Success)
ErrorException: 1: Interface 'PHPCI\Plugin' not found in /var/www/html/vendor/ket4yii/phpci-deployer-plugin/Plugin/Deployer.php line 19 (uncaught exception) at /var/www/html/vendor/ket4yii/phpci-deployer-plugin/Plugin/Deployer.php line 19

**Comment by ket4yii** [comment]
And after that I can't up a worker. Because of this:

worker_1  | [2017-03-16 21:15:18] WorkerCommand.INFO: Received build #5 from Beanstalkd [] []
worker_1  | [2017-03-16 21:15:18] WorkerCommand.WARNING: Build #5 does not exist in the database. [] []
worker_1  | 
worker_1  |                                                                                                     
worker_1  |   [ErrorException]                                                                                  
worker_1  |   Notice: Undefined variable: build in /var/www/html/src/PHPCensor/Worker/BuildWorker.php line 130 

It didn't disappear after worker restart

**Comment by corpsee** [comment]
Yes, I changed PHPCI\Plugin interface to base Plugin class (I refactored plugins at the beginning of PHP Censor). I see two ways now:
1. Create separate PHP Censor plugin (php-censor-deployer-plugin in separate repository). (Like [PHP-Censor-Telegram-Plugin](https://github.com/LEXASOFT/PHP-Censor-Telegram-Plugin))
2. Add you plugin to main PHP Censor repository

**Comment by corpsee** [comment]
@ket4yii If you will create separate repository, I may help to fix plugin for PHP Censor.

**Comment by ket4yii** [comment]
It's done:)
