### ISSUE TITLE
Not necessary message about nonexistent update command

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#4]
If config.yml exists and you run install command  it shows you message about update command, but this command has been deleted. I think [this line](https://github.com/corpsee/php-censor/blob/master/src/PHPCensor/Command/InstallCommand.php#L470) is redundant

**Comment by corpsee** [comment]
Yes, you are right. Thanks.
I'm just doing a little commands refactoring in the separate branch, where it will be fixed.

**Comment by corpsee** [comment]
Fix in master. @ket4yii, Can you check it?

**Comment by ket4yii** [comment]
@corpsee It's ok. You can close it.
