### ISSUE TITLE
Adding support for Wordpress Coding Standards

### ISSUE THREAD

**Issue by SMstevesf** [corpsee/php-censor#43]
Is there a way to add support for https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards in this current implementation. I tried installing and adding a custom route to the XML file, but CodeSniffer fails. `"WordPress-Core" coding standard is not installed. The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend` is the error I get.

**Comment by corpsee** [comment]
Hi! I'll try to check it tonight. Thank you for feedback!

**Comment by ValerioOnGithub** [comment]
Hello

Could you please try the following?
1. Add phpcs and wpcs to your composer.json
```
composer require squizlabs/php_codesniffer
composer require wp-coding-standards/wpcs
```

2. Modify the phpcs section in your .php-censor.yml:
```
test:
    php_code_sniffer:
	....
        standard: "WordPress-Core"
	....
```
 
It should work. The path to ruleset will be automaticaly set by composer after install/update (see [composer.json](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/composer.json)).

**Comment by ValerioOnGithub** [comment]
Update:
> The path to ruleset will be automaticaly set by composer after install/update (see composer.json).

It doesn't work if you use wpcs as dependency so:
3. Update composer.json with the following:
`"scripts": {
    "post-install-cmd": "\"vendor/bin/phpcs\" --config-set installed_paths ../../../vendor/wp-coding-standards/wpcs",
    "post-update-cmd" : "\"vendor/bin/phpcs\" --config-set installed_paths ../../../vendor/wp-coding-standards/wpcs"
}`

**Comment by corpsee** [comment]
@ValerioOnGithub Thx!

**Comment by SMstevesf** [comment]
@ValerioOnGithub @corpsee Thanks for the quick replies. I'll give this a tweak and see if it works.

**Comment by SMstevesf** [comment]
This works great! Thanks for the help
