### ISSUE TITLE
Exception when run plugin without options

### ISSUE THREAD

**Issue by bochkovprivate** [corpsee/php-censor#44]
I have a project like this:
```
...
test:
    php_parallel_lint:
    php_unit:
        config:
            - "test/phpunit.xml"
```
When I run the build it fails with messages like this:
```
RUNNING PLUGIN: PHP Parallel Lint (Stage: Test)
Exception: Catchable Fatal Error: Argument 3 passed to PHPCensor\Plugin\PhpParallelLint::__construct() must be of the type array, null given in /var/www/php-censor/src/PHPCensor/Plugin/PhpParallelLint.php line 46
PLUGIN: FAILED
```

This happens for all plugins I ran without params. That is not the desired behaviour because all params for these plugins are optional.

The same time in PHPCI this configurations works.

If I add params than it works like a charm in php-censor.

Looks like the reason is the difference between php-censor and PHPCI here:
* https://github.com/Block8/PHPCI/blob/master/PHPCI/Plugin/Util/Factory.php
* https://github.com/corpsee/php-censor/blob/master/src/PHPCensor/Plugin/Util/Factory.php
I see difference in the constructor and in the buildPlugin method in it's foreach cycle.

**Comment by corpsee** [comment]
Thx @bochkovprivate! Fixed in master branch. Can you check it?

**Comment by bochkovprivate** [comment]
Not working yet.
The options now occasionally pass from one plugin to anther. Here is what it looks like in the console:
```
RUNNING PLUGIN: MySQL (Stage: Setup)
Plugin options: ["CREATE DATABASE rfm_db_test_%BUILD%;","CREATE DATABASE rfm_db_test_%BUILD%_%ENVIRONMENT%;"]
PLUGIN: SUCCESS

RUNNING PLUGIN: Shell (Stage: Setup)
Plugin options: ["CREATE DATABASE rfm_db_test_%BUILD%;","CREATE DATABASE rfm_db_test_%BUILD%_%ENVIRONMENT%;"]
Args: ["CREATE DATABASE rfm_db_test_48;"]
Command: CREATE DATABASE rfm_db_test_48;
sh: CREATE: command not found
```

**Comment by corpsee** [comment]
I will try to fix it...

**Comment by corpsee** [comment]
@bochkovprivate I fixed this problem in branch `bugfix-44`. Can you check it, please?

**Comment by bochkovprivate** [comment]
Yes, now it works!
Thanks for great work man.

**Comment by corpsee** [comment]
No problem :smile:
