### ISSUE TITLE
Not optimal implementation of error recording

### ISSUE THREAD

**Issue by ss-gxp** [corpsee/php-censor#49]
Inserting errors into the database table occurs one at a time, which is not optimal. The real situation is the testing of legacy project, which generated more than 70 thousand errors. Testing went for more than an hour, and a significant part in my opinion is a record in the database. Using the bulk insert, can significantly increase the speed. In the current architecture, this is not possible, I suggest changing to `ErrorWriter` and `ErrorReader`.

Are there any other ideas?

**Comment by corpsee** [comment]
It sounds good. About `ErrorWriter` It is ok, but I not quite understend what for  `ErrorReader`.
Anyway I can tell something when I saw Pull Request and code if you going to make this enchancement. Thanks.

**Comment by corpsee** [comment]
Fixed in #50
