### ISSUE TITLE
[Question] How can I initialize phpcensor?

### ISSUE THREAD

**Issue by ketchoop** [corpsee/php-censor#5]
If I've got config.yml I can't use **install** command, but I have to initialize database and beanstalk queue. And there is no update command in **console**.

**Comment by ket4yii** [comment]
Oh, I found migration command. A problem with db initialization have been solved. Let me check how beanstalk queue and and if there are no problems with it I'm going to close this issue.

**Comment by ket4yii** [comment]
It's OK. It was too impatient to open this issue, sorry.

**Comment by corpsee** [comment]
That's all right) By the way, cron-worker doesn't need queue (It is may be skipped), but worker need.

**Comment by ket4yii** [comment]
I think cron worker really strange and bad thing. I'm gonna make worker containers with worker command as entrypoint. You can't move cron-workers to separate servers and it's really strange think to use cron for making infinite loop just to check build queue(I'm not really familiar with PHP core, but there are no ways to make loop, aren't there?). Also, in docs there are many strange things like using supervisord to just daemonize worker(why just don't use nohup?).

**Comment by corpsee** [comment]
Cron is normal solving for one worker and every minute restart ensures that worker runs.
You may run worker without supervisord with nohub, but if worker crashed, it won't up.

P.S.: I think that you may use SystemD instead of SupervisorD for demonization theoreticaly)

**Comment by ket4yii** [comment]
> you may use SystemD

Yes, I know. But it was about big size of supervisord and doing more steps to just run script in daemon mode:smile:. But it's not important. Anyway, I think it would be great to write about it in the docs.

**Comment by corpsee** [comment]
@ket4yii Now you can use install command with config.yml instead options (excluding admin options):
```bash
# Non-interactive installation with prepared config.yml file
./bin/console php-censor:install --config-from-file=yes --admin-name=admin --admin-password=admin --admin-email='admin@php-censor.local'
```

**Comment by ket4yii** [comment]
It's so good feature. I'm gonna change docker image according to this feature

**Comment by corpsee** [comment]
**Note**: Discribe SystemD configuration instead of SupervisorD.

**Comment by corpsee** [comment]
See #98.
