### ISSUE TITLE
Missing Slack Lib

### ISSUE THREAD

**Issue by SMstevesf** [corpsee/php-censor#53]
Great work on this. Running the Slack integration and I get an error 
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Maknz\Slack\Client' not found`
When looking at your composer.json, I don't see this as being pulled in.

**Comment by corpsee** [comment]
Add into your composer.json `require` section:
```yml
"maknz/slack": "1.7.*",
```
I don't see the point of adding it into distr `require` section, but I will add it into `suggest` section.
Thanks @SMstevesf!

**Comment by SMstevesf** [comment]
Thanks for the update and the quick reply. I'll give this a shot.

**Comment by corpsee** [comment]
Don't close the issue please. Thanks.

**Comment by SMstevesf** [comment]
No worries, I'll leave it open for you 😄
