### ISSUE TITLE
Where can I find phpcensor logs. 

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#59]
It's not obvious. For example, I've got error about database and I can see it, when I try to create new admin, but, you know, it shouldn't be this way :). I know, it's silly question but, It's harmful to get into source code and try to find out where logger is configured.

**Comment by corpsee** [comment]
You need to create `loggerconfig.php` file in `app` directory with content like:
```php
<?php

return [
    /** Loggers attached to every command */
    "_" => function() {
        return [
            new \Monolog\Handler\StreamHandler(RUNTIME_DIR . 'errors.log', \Monolog\Logger::ERROR),
        ];
    }
];
```

It should helps you.

**Comment by corpsee** [comment]
I will plan to remove this ugly config and move logging settings to main application config.

**Comment by corpsee** [comment]
Fixed.
