### ISSUE TITLE
[Bug] Postgresql default port.

### ISSUE THREAD

**Issue by ket4yii** [corpsee/php-censor#6]
If somebody use postgresql as backend database for phpcensor he have to explicitly pass database port even this port is standard for postgresql. I think phpcensor pass to phinx default mysql port.

**Comment by corpsee** [comment]
I fixed that in separate branch. I will merge branch when have made all changes.

**Comment by ket4yii** [comment]
Thanks.

**Comment by corpsee** [comment]
I will close the isssue when I will merge branch

**Comment by corpsee** [comment]
Fix in master. @ket4yii, Can you check it?

**Comment by ket4yii** [comment]
It's ok. But in console message default port is shown empty. 
Log:

```
Please enter your database port (default: empty)
```

**Comment by corpsee** [comment]
It is ok, [empty] means that will be used connection without explicit port.
