### ISSUE TITLE
Use webhook for bitbucket

### ISSUE THREAD

**Issue by DarkhejMaster** [corpsee/php-censor#64]
Can I use Bitbucket webhooks for the webhook link instead of POST service?

**Comment by corpsee** [comment]
Can you explain more in details what you mean (with links to Bitbucket documentation)? You need that PHP Censor instance call Bitbucket?

P.S.: In any case, now is exists only webhook from Bitbucket ([Bitbucket docs](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html) and [PHP Censor docs](https://github.com/corpsee/php-censor/blob/master/docs/en/sources/bitbucket.md)).

**Comment by corpsee** [comment]
Do you ask about [this](https://github.com/Block8/PHPCI/pull/1038)? If yes then your case should work.

**Comment by DarkhejMaster** [comment]
I confirm that it's working (at least for me)
![bitbucket webhooks](https://cloud.githubusercontent.com/assets/17334751/25861240/6053fb30-34e4-11e7-9189-37f417f39b7f.png)
![phpci](https://cloud.githubusercontent.com/assets/17334751/25861241/608181b8-34e4-11e7-9710-05e84dedd6a0.png)

**Comment by corpsee** [comment]
Excellent! Thank you for testing.
