### ISSUE TITLE
Project conf - SVN - Default branch not used

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#65]
In SVN project, if there is default branch name specified, it's not used.
Repo URL : https://user:password@uri/to/svn/project
Default branch name : my-branch
Error : 
![image](https://cloud.githubusercontent.com/assets/4368255/26153119/54f065cc-3b0a-11e7-98a6-1245259dc1c7.png)

It's always "master" and not "my-branch"

**Comment by corpsee** [comment]
Thank you for the report, @BrunoJunior.

**Comment by corpsee** [comment]
I tryed to fix branches for SVN. @BrunoJunior Can you test it (PHP Censor from branch `bugfix-svn`)?
Try to create 2 new projects with:

1. **Repository Name / URL (Remote) or Path (Local)**: "https://user:password@uri/to/svn/project" (URL without trunk/branches etc.) and **Default branch name**: ""
2. **Repository Name / URL (Remote) or Path (Local)**: "https://user:password@uri/to/svn/project" (URL without trunk/branches etc.) and **Default branch name**: "my-branch"

In first case branch will `/trunk` (default from empty string) and in second case branch will `/branches/my-branch`.

**Comment by BrunoJunior** [comment]
OK
Bug fixed
I'll open an issue to make possible to change the default branch repo. (branches by default)
