### ISSUE TITLE
SVN - Possibility to change branches repo name

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#67]
Add a text area where SVN was chosen.
Default branch repo.
With "branches" by default.
Some SVN projects do not respect the default branches model

**Comment by corpsee** [comment]
I think it will be easier refactor the logic of SVN branches, so that it was necessary to set the full name of the branch (unlike git). Like `branches/my-branch` instead of `my-branch`.
What do you think @BrunoJunior? Thanks.

**Comment by BrunoJunior** [comment]
I think it could be great !
I don't know if you know Jenkins (Hudson), but in the SVN plugin, when you set the url up, you have to set the complete url.
It could be enough ?
![image](https://cloud.githubusercontent.com/assets/4368255/26544867/d1652eb4-4463-11e7-84b7-1f1d9365cfa1.png)

**Comment by corpsee** [comment]
Fixed. Add optional ability to set branch full name like "branches/branch-1" or "/branch/branch-2".
