### ISSUE TITLE
Atoum - Tests are not launched

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#69]
First of all, I ran same tests on my dev machine.
Command line generated by Netbeans (on Windows) :
"C:\path\to\global\Composer\vendor\bin\atoum.bat" "-d" "C:\path\to\project\test" "-utr" "-bf" "C:\path\to\project\test\.bootstrap.atoum.php"
I had atoum option in test in php-censor.yml :
```
test:
  atoum:
    directory: "test"
```
Plugin result :
![image](https://cloud.githubusercontent.com/assets/4368255/26198682/4898e4d0-3bc7-11e7-93e2-54797ded31a5.png)

Other plugins show args and launched cmd line, but here, I have nothing at all ...
Had I to add args myself in args option ?
Can I put relative filepathes in args option ?

**Comment by BrunoJunior** [comment]
I changed conf :
```yaml
test:
  atoum:
    args: "-utr -d ./test -bf ./test/.bootstrap.atoum.php"
```
Tests ran and all passed but I had PLUGIN ERROR, why ?
![image](https://cloud.githubusercontent.com/assets/4368255/26201722/9ba88d9e-3bd4-11e7-8c61-f0673b0976b9.png)

**Comment by corpsee** [comment]
Thanks for the report, @BrunoJunior. I think it is plugin bug (Atoum plugin is too old and doesn't enough tested). I will try to refactor it soon.

**Comment by BrunoJunior** [comment]
OK I removed -utr arg and build passed ...
Is there atoum tests results anywhere like code lines or quality charts ?

**Comment by corpsee** [comment]
As far as I can see (in code), no. It is very simple plugin.

**Comment by corpsee** [comment]
#72
