### ISSUE TITLE
Build run error

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#71]
I ran a build with success.
Maybe 5 minutes later I run another build.
I had this error
![image](https://cloud.githubusercontent.com/assets/4368255/26202520/06505070-3bd8-11e7-8565-ee3b5c38ee1e.png)
I restarted my VM, re run the build, and no more error ...

**Comment by corpsee** [comment]
Thanks @BrunoJunior.

**Comment by corpsee** [comment]
@BrunoJunior I am closing this issue for now because this problem appeared once. Feel free for reopen this issue if problem will repeat again.
