### ISSUE TITLE
Installation Error - Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#73]
I tried to install php-censor on a VM wich runs Debian with postgresql (without MySQL - I didn't activate pdo_mysql, because I want to use Postgresql ...) and I had this error : 
> PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /vagrant/php-censor.local/src/PHPCensor/Command/InstallCommand.php on line 429
PHP Stack trace:
PHP   1. {main}() /vagrant/php-censor.local/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /vagrant/php-censor.local/bin/console:11
PHP   3. Symfony\Component\Console\Application->doRun() /vagrant/php-censor.local/vendor/symfony/console/Application.php:123
PHP   4. Symfony\Component\Console\Application->doRunCommand() /vagrant/php-censor.local/vendor/symfony/console/Application.php:192
PHP   5. Symfony\Component\Console\Command\Command->run() /vagrant/php-censor.local/vendor/symfony/console/Application.php:846
PHP   6. PHPCensor\Command\InstallCommand->execute() /vagrant/php-censor.local/vendor/symfony/console/Command/Command.php:264
PHP   7. PHPCensor\Command\InstallCommand->verifyDatabaseDetails() /vagrant/php-censor.local/src/PHPCensor/Command/InstallCommand.php:86

**Comment by corpsee** [comment]
Hello, @BrunoJunior. Thank you for the useful report! I fixed this bug in branch `bugfix-issue-73`. Can you check it?

**Comment by BrunoJunior** [comment]
I have another error ...
I cloned project in my VM with git clone ...
I switched into remotes/origin/bugfix-issue-73
I ran composer install
I ran ./bin/console php-censor:install

I have this error : 
> file_put_contents(/vagrant/php-censor/app/config.yml): failed to open stream: No such file or directory in /vagrant/php-censor/src/PHPCensor/Command/InstallCommand.php line 458

Why APPDIR add an app directory ? Did I do something wrong ?

**Comment by corpsee** [comment]
Sorry, It is bug in the fresh `master` branch. I fixed it just now. Try again)

**Comment by BrunoJunior** [comment]
Setup done !
