### ISSUE TITLE
create admin args

### ISSUE THREAD

**Issue by vinpel** [corpsee/php-censor#8]
Hello, 
Could you add the "$input->getOption" to be able to create an admin from command line with response e in /src/PHPCensor/Command/CreateAdminCommand.php like it's done in install ?

Thanks you

**Comment by corpsee** [comment]
I thought about this too. May I ask: for what purpose you use this command?

**Comment by vinpel** [comment]
the goal is to start a container, if no php-censor install create one.
actualy i do :
  * Call install with all command line arguments an admin is created, (fixed the host=>port type in 0.7)
  * Replace the config.yml generated with a fully configured (worker ...) from container arguments

**Comment by corpsee** [comment]
* Now config.yml have all options after installation (See https://github.com/corpsee/php-censor/blob/master/src/PHPCensor/Command/InstallCommand.php#L250)

* Now you can install PHP Censor non-interactive with prepared config.yml:

```bash
# Non-interactive installation with prepared config.yml file
./bin/console php-censor:install --config-from-file=yes --admin-name=admin --admin-password=admin --admin-email='admin@php-censor.local'
```
Today I have merged this changes into master. They will be included in version 0.8.0.

After that, the command CreateAdminCommand must become useless, right?

**Comment by vinpel** [comment]
If i start a container with a config.yml, i may not have the same admin password so  i want to be sure, setting it again, so create admin on an existing configured php-censor instance.

**Comment by corpsee** [comment]
Oк, I understood. Thanks.

**Comment by corpsee** [comment]
Done.

**Comment by vinpel** [comment]
thanks love it

**Comment by corpsee** [comment]
You are welcome!
