### ISSUE TITLE
Upgrade SwiftMailer from 5.x to 6.x major version. 

### ISSUE THREAD

**Issue by corpsee** [corpsee/php-censor#80]
Upgrade SwiftMailer from 5.x to 6.x major version.

To upgrade SwiftMailer It Should remote `Swift_MailTransport` and `Swift_Transport_MailTransport` from project because it is deprecated in 6 version.

According to #79.

**Comment by StudioMaX** [comment]
Don't forget that SwiftMailer 6 has a requirement on PHP ^7.0.

**Comment by corpsee** [comment]
Oh... T_T Than 5.x remains. Thank you @StudioMaX.
