### ISSUE TITLE
[Feature] overwrite part of config locally

### ISSUE THREAD

**Issue by SimonHeimberg** [corpsee/php-censor#87]
Sometimes it would be handy to have the project configuration in .php-censor.yml but set some parts local only.
To copy the entire project config to the local config (in db) is not very handy.

Maybe the database name is different locally, maybe I have to include some secrets, ...

In #14, there is requested to set some config parts secretly. (Probably more secret than here.)

**Comment by corpsee** [comment]
Ok, I will think about it. Thanks!

**Comment by SimonHeimberg** [comment]
Configuration could probably be similar to configuring a branch (branch-dev in [configuring_project.md](../blob/master/docs/en/configuring_project.md). (To define before/after/overwrite, ... maybe more granular than only for the entire stage, but prepend some plugins, append some, ...)
Setting some parameters would be handy (db_name, ...).

Some use-cases:
 * other name of the database
 * other database backend (mysql/sqlite/*)
 * set local parameters (host name, port, password, ...)

**Comment by SimonHeimberg** [comment]
With local parameters (#14, when usable in yaml), above use-cases can be covered.

For the rest, it is probably simpler to call a local shell script which must be in a certain place:
```yml
    shell:
        - |
            scriptPath=%PROJECT_BUILD_PATH%/../../hook-path/prepare-test5.sh
            [ -f $scriptPath ] && $scriptPath
```

I am fine with closing this issue.

**Comment by corpsee** [comment]
Thank you for the detail explanation. Ok, I close this issue.

**Comment by corpsee** [comment]
I implemented ability to merge in-database project config over in-repository file config (`.php-censor.yml`). See [commit](https://github.com/php-censor/php-censor/commit/069026bc2d6f34bbf6b4853938a3f9d54f90eed9).

You may disable `overwrite_build_config` checkbox in the project editing/adding page and in-database project config will be merged over in-repository config without full replace.

It solve secret information case #14 and `clone_depth` option problem #106.
