### ISSUE TITLE
links from error page should link to hash, not branch

### ISSUE THREAD

**Issue by SimonHeimberg** [corpsee/php-censor#89]
Errors create links to the lines on github. This is great. But the link is to the branch and not the commit id. This will result in the wrong line when when anything is pushed to this branch later, adding or removing some lines before.

current:
https://github.com/corpsee/php-censor/blob/master/src/PHPCensor/Model/Build/GithubBuild.php#L141

proposed:
https://github.com/corpsee/php-censor/blob/9041457af4316c18784665875529c1dfcf8a4be9/src/PHPCensor/Model/Build/GithubBuild.php#L141

For github urls, the file linked above can be adapted. But I have not yet checked if `getFileLinkTemplate()` is used elsewhere. And I did not check if other buildTypes should be adapted too.

I can create a pullrequest when I know what to do.

**Comment by corpsee** [comment]
Thanks! I will wait for your request.

**Comment by SimonHeimberg** [comment]
Note:
`getFileLinkTemplate()` is used on error page and on lint plugin, so adapting this function should be fine...
