### ISSUE TITLE
limit of 65535 characters for meta_value of build_meta with mysql

### ISSUE THREAD

**Issue by SimonHeimberg** [corpsee/php-censor#94]
In my instance, the value of phpunit-data is silently cut to 65535 characters. This results in invalid json, so no results for phpunit are shown on the information tab.

The value for phpunit-data is stored in `build_meta.meta_value`. This field has type `text`.
The size limit for text is 65535: https://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html#idm140523574444128

How should this be fixed? Store less data in this column for `phpunit-data`? Use another column type for mysql (MEDIUMTEXT, ...)?

**Comment by corpsee** [comment]
I will change column type for MySQL to something large. Thanks @SimonHeimberg for the report.

**Comment by corpsee** [comment]
Fixed in fresh `master` branch.
